logging:
  level:
    root: trace
#    root: warn
#    org:
#      apache: warn
#      spark_project: warn
spark:
  deployMode: client
  master: local[*]
  appName: spark-kafka-example
  offHeapMemoryGb: 4
kafka:
  bootstrapServers: node-3:9092
  consumerGroup: spark.test.group
  keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
  valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
  topics: spark.test
  enabled: false
database:
  username: dwUser
  password: Password01
  jdbcUrl: jdbc:sqlserver://biwfmdm-datavault-member-1.mia.ucloud.int;Database=WFM_DATAMART